package edu.unh.rbooking.table;
// default package
// Generated Dec 3, 2016 3:39:47 PM by Hibernate Tools 5.2.0.Beta1

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonManagedReference;

import edu.unh.rbooking.employee.EmployeeBO;
import edu.unh.rbooking.reservation.ReservationTableMappingBO;

/**
 * Table generated by hbm2java
 */
public class TableBO implements java.io.Serializable {

	private Integer id;

	@JsonBackReference
	private EmployeeBO employee;
	private Integer numberPeople;
	private List<ReservationTableMappingBO> reservationTableMappings = new ArrayList<ReservationTableMappingBO>(0);

	public TableBO() {
	}

	public TableBO(EmployeeBO employee) {
		this.employee = employee;
	}

	public TableBO(EmployeeBO employee, Integer numberPeople, List<ReservationTableMappingBO> reservationTableMappings) {
		this.employee = employee;
		this.numberPeople = numberPeople;
		this.reservationTableMappings = reservationTableMappings;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public EmployeeBO getEmployee() {
		return this.employee;
	}

	public void setEmployee(EmployeeBO employee) {
		this.employee = employee;
	}

	public Integer getNumberPeople() {
		return this.numberPeople;
	}

	public void setNumberPeople(Integer numberPeople) {
		this.numberPeople = numberPeople;
	}

	public List<ReservationTableMappingBO> getReservationTableMappings() {
		return this.reservationTableMappings;
	}

	public void setReservationTableMappings(List<ReservationTableMappingBO> reservationTableMappings) {
		this.reservationTableMappings = reservationTableMappings;
	}

}
