package edu.unh.rbooking.table;
// default package
// Generated Dec 3, 2016 3:39:47 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

import edu.unh.rbooking.employee.EmployeeDO;
import edu.unh.rbooking.reservation.ReservationTableMappingDO;

/**
 * Table generated by hbm2java
 */
public class TableDO implements java.io.Serializable {

	private Integer id;
	private EmployeeDO employee;
	private Integer numberPeople;
	private Set<ReservationTableMappingDO> reservationTableMappings = new HashSet<ReservationTableMappingDO>(0);

	public TableDO() {
	}

	public TableDO(EmployeeDO employee) {
		this.employee = employee;
	}

	public TableDO(EmployeeDO employee, Integer numberPeople, Set<ReservationTableMappingDO> reservationTableMappings) {
		this.employee = employee;
		this.numberPeople = numberPeople;
		this.reservationTableMappings = reservationTableMappings;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public EmployeeDO getEmployee() {
		return this.employee;
	}

	public void setEmployee(EmployeeDO employee) {
		this.employee = employee;
	}

	public Integer getNumberPeople() {
		return this.numberPeople;
	}

	public void setNumberPeople(Integer numberPeople) {
		this.numberPeople = numberPeople;
	}

	public Set<ReservationTableMappingDO> getReservationTableMappings() {
		return this.reservationTableMappings;
	}

	public void setReservationTableMappings(Set<ReservationTableMappingDO> reservationTableMappings) {
		this.reservationTableMappings = reservationTableMappings;
	}

}
