package edu.unh.rbooking.reservation;
// default package
// Generated Dec 3, 2016 3:39:47 PM by Hibernate Tools 5.2.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonManagedReference;

import edu.unh.rbooking.customer.CustomerBO;

/**
 * Reservation generated by hbm2java
 */
public class ReservationBO implements java.io.Serializable {

	private Integer id;
	
	private CustomerBO customer;
	private Integer numberPeople;
	private String time;
	private Date date;
	private Boolean hasShowup;
	private List<ReservationTableMappingBO> reservationTableMappings = new ArrayList<ReservationTableMappingBO>(0);

	public ReservationBO() {
	}

	public ReservationBO(CustomerBO customer) {
		this.customer = customer;
	}

	public ReservationBO(CustomerBO customer, Integer numberPeople, String time, Date date, Boolean hasShowup,
			List<ReservationTableMappingBO> reservationTableMappings) {
		this.customer = customer;
		this.numberPeople = numberPeople;
		this.time = time;
		this.date = date;
		this.hasShowup = hasShowup;
		this.reservationTableMappings = reservationTableMappings;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CustomerBO getCustomer() {
		return this.customer;
	}

	public void setCustomer(CustomerBO customer) {
		this.customer = customer;
	}

	public Integer getNumberPeople() {
		return this.numberPeople;
	}

	public void setNumberPeople(Integer numberPeople) {
		this.numberPeople = numberPeople;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Boolean getHasShowup() {
		return this.hasShowup;
	}

	public void setHasShowup(Boolean hasShowup) {
		this.hasShowup = hasShowup;
	}

	public List<ReservationTableMappingBO> getReservationTableMappings() {
		return this.reservationTableMappings;
	}

	public void setReservationTableMappings(List<ReservationTableMappingBO> reservationTableMappings) {
		this.reservationTableMappings = reservationTableMappings;
	}

}
