package edu.unh.rbooking.reservation;
// default package
// Generated Dec 3, 2016 3:39:47 PM by Hibernate Tools 5.2.0.Beta1

import edu.unh.rbooking.table.TableDO;

/**
 * ReservationTableMapping generated by hbm2java
 */
public class ReservationTableMappingDO implements java.io.Serializable {

	private ReservationTableMappingIdDO id;
	private ReservationDO reservation;
	private TableDO table;

	public ReservationTableMappingDO() {
	}

	public ReservationTableMappingDO(ReservationTableMappingIdDO id, ReservationDO reservation, TableDO table) {
		this.id = id;
		this.reservation = reservation;
		this.table = table;
	}

	public ReservationTableMappingIdDO getId() {
		return this.id;
	}

	public void setId(ReservationTableMappingIdDO id) {
		this.id = id;
	}

	public ReservationDO getReservation() {
		return this.reservation;
	}

	public void setReservation(ReservationDO reservation) {
		this.reservation = reservation;
	}

	public TableDO getTable() {
		return this.table;
	}

	public void setTable(TableDO table) {
		this.table = table;
	}

}
