package edu.unh.rbooking.reservation;
// default package
// Generated Dec 3, 2016 3:39:47 PM by Hibernate Tools 5.2.0.Beta1

import edu.unh.rbooking.table.TableBO;

/**
 * ReservationTableMapping generated by hbm2java
 */
public class ReservationTableMappingBO implements java.io.Serializable {

	private ReservationTableMappingIdBO id;
	private ReservationBO reservation;
	private TableBO table;

	public ReservationTableMappingBO() {
	}

	public ReservationTableMappingBO(ReservationTableMappingIdBO id, ReservationBO reservation, TableBO table) {
		this.id = id;
		this.reservation = reservation;
		this.table = table;
	}

	public ReservationTableMappingIdBO getId() {
		return this.id;
	}

	public void setId(ReservationTableMappingIdBO id) {
		this.id = id;
	}

	public ReservationBO getReservation() {
		return this.reservation;
	}

	public void setReservation(ReservationBO reservation) {
		this.reservation = reservation;
	}

	public TableBO getTable() {
		return this.table;
	}

	public void setTable(TableBO table) {
		this.table = table;
	}

}
