package edu.unh.rbooking.customer;
// default package
// Generated Dec 3, 2016 3:39:47 PM by Hibernate Tools 5.2.0.Beta1

import java.util.ArrayList;
import java.util.List;

import edu.unh.rbooking.reservation.ReservationDO;

/**
 * Customer generated by hbm2java
 */
public class CustomerDO implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String lastName;
	private String phone;
	private String email;
	private List<ReservationDO> reservations = new ArrayList<ReservationDO>(0);

	public CustomerDO() {
	}

	public CustomerDO(String firstName, String lastName, String phone, String email, List<ReservationDO> reservations) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.phone = phone;
		this.email = email;
		this.reservations = reservations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public List<ReservationDO> getReservations() {
		return this.reservations;
	}

	public void setReservations(List<ReservationDO> reservations) {
		this.reservations = reservations;
	}

}
