package edu.unh.rbooking.credential;
// default package
// Generated Dec 3, 2016 3:39:47 PM by Hibernate Tools 5.2.0.Beta1

import org.codehaus.jackson.annotate.JsonBackReference;

import edu.unh.rbooking.employee.EmployeeBO;

/**
 * Credential generated by hbm2java
 */
public class CredentialBO implements java.io.Serializable {

	private Integer id;
	
	@JsonBackReference
	private EmployeeBO employee;
	private String userName;
	private String password;

	public CredentialBO() {
	}

	public CredentialBO(EmployeeBO employee) {
		this.employee = employee;
	}

	public CredentialBO(EmployeeBO employee, String userName, String password) {
		this.employee = employee;
		this.userName = userName;
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public EmployeeBO getEmployee() {
		return this.employee;
	}

	public void setEmployee(EmployeeBO employee) {
		this.employee = employee;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
